
// Auto-generated by doxy2swig. Do not edit.

// File: index.xml

// File: simple_8cc.xml
%feature("docstring")  gcd "int gcd(int x, int y)

Compute the greatest common divisor of positive integers ";

