! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module simplest
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! PUBLIC METHODS AND TYPES
 public :: add

 ! WRAPPER DECLARATIONS
 interface
function add(a, b) &
bind(C, name="add") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), value :: a
integer(C_INT), value :: b
integer(C_INT) :: fresult
end function

 end interface


end module
