
# failed to compile wrapper
FAILING_CPP_TESTS += \
  abstract_typedef2 \
  apply_signed_char \
  apply_strings \
  array_member \
  arrays_dimensionless \
  arrays_global \
  bloody_hell \
  char_binary \
  char_strings \
  constant_directive \
  constant_pointers \
  cpp_enum \
  cpp_namespace \
  director_enum \
  director_string \
  enum_ignore \
  enum_thorough \
  exception_order \
  global_namespace \
  global_vars \
  ignore_template_constructor \
  li_boost_shared_ptr_bits \
  li_cdata_cpp \
  li_std_combinations \
  li_std_vector \
  li_std_vector_enum \
  li_std_vector_ptr \
  li_typemaps \
  li_typemaps_apply \
  li_windows \
  long_long_apply \
  member_funcptr_galore \
  mixed_types \
  namespace_typemap \
  naturalvar_more \
  primitive_ref \
  reference_global_vars \
  register_par \
  sizet \
  smart_pointer_inherit \
  smart_pointer_multi_typedef \
  smart_pointer_typedef \
  template_basic \
  template_default_arg \
  template_explicit \
  template_ns2 \
  template_ns_enum \
  template_opaque \
  template_type_namespace \
  template_whitespace \
  threads_exception \
  typedef_array_member \
  typedef_struct_cpp \
  typemap_directorout \
  typemap_template_parm_typedef \
  virtual_poly

# failed to compile fortran
FAILING_CPP_TESTS += \
  abstract_signature \
  arrays_scope \
  class_ignore \
  class_scope_weird \
  constructor_copy \
  contract \
  cpp_basic \
  cpp_typedef \
  default_constructor \
  derived_nested \
  director_basic \
  director_classes \
  director_default \
  director_detect \
  director_frob \
  director_ignore \
  director_keywords \
  director_overload2 \
  director_property \
  enum_scope_template \
  evil_diamond_prop \
  extend \
  extend_default \
  friends_template \
  fvirtual \
  global_scope_types \
  inherit_missing \
  inherit_target_language \
  kind \
  li_attribute \
  li_attribute_template \
  li_boost_shared_ptr \
  member_pointer_const \
  multiple_inheritance_abstract \
  multiple_inheritance_interfaces \
  multiple_inheritance_nspace \
  multiple_inheritance_shared_ptr \
  namespace_class \
  namespace_nested \
  namespace_virtual_method \
  nested_class \
  nested_ignore \
  nested_scope \
  nested_workaround \
  operator_overload \
  operator_overload_break \
  overload_arrays \
  overload_method \
  overload_polymorphic \
  overload_return_type \
  overload_simple \
  overload_subtype \
  overload_template \
  overload_template_fast \
  pod_struct \
  pure_virtual \
  refcount \
  return_const_value \
  smart_pointer_const_overload \
  smart_pointer_ignore \
  smart_pointer_rename \
  smart_pointer_template_const_overload \
  smart_pointer_template_defaults_overload \
  special_variables \
  template_arg_scope \
  template_arg_typename \
  template_default \
  template_default_vw \
  template_enum \
  template_extend_overload \
  template_forward \
  template_inherit_abstract \
  template_methods \
  template_nested \
  template_ns \
  template_ns_enum2 \
  template_ref_type \
  template_retvalue \
  template_typedef_class_template \
  template_typedef_cplx5 \
  template_typedef_inherit \
  template_typemaps \
  template_typemaps_typedef \
  template_typemaps_typedef2 \
  template_using_directive_and_declaration_forward \
  typemap_ns_using \
  typemap_various \
  using1 \
  using2 \
  using_inherit \
  using_protected \
  valuewrapper_base \
  valuewrapper_opaque \
  variable_replacement \
  wallkw
